apiVersion: v2
name: discsync
description: discsync
type: application
version: 0.3.0
appVersion: 0.3.0
dependencies:
  - name: single-container
    version: "1.x.x"
    repository: "oci://ghcr.io/vaughnw128/charts"
