single-container:
  name: "discsync"
  image: "ghcr.io/vaughnw128/discsync"
  imageTag: "0.3.0"
  containerPort: 8080
  gateway:
    enabled: false
  db:
    enabled: true
    secretName: "sbux-oracle-pg-app"
    uriKey: "uri-pooler-rw"
  secretVars:
    DISCORD_TOKEN: "discsync-discord-token/credential"
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 2048Mi
      cpu: 1024m
