name: Code Quality & Tests
on:
  push:
    branches:
      - main
  pull_request: # Run on all PR branches

jobs:
  code-quality:
    name: "Code Quality"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Add rustfmt
        run: "rustup component add rustfmt"

      - name: Add clippy
        run: "rustup component add clippy"

      - name: Code Format
        run: "cargo fmt"

      - name: Linting
        run: "cargo clippy"

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Helm Lint
        run: helm lint helm/

      - name: Helm Template
        run: helm template helm/

        # Don't run these next steps if it's not a PR build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
        with:
          push: false

  tests:
    name: "Test Suites"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Test
        run: cargo test